[workspace]
members = [
    "libraries/Microservice",
    "user/Accounts/server",
    "user/UserStore/server",
    "matches/Factory/server",
    "matches/Registry/server",
    "matches/StubMatchmaking/server",
    "matches/StubRegistry/server",
    "matches/Realtime/server/",
    "matches/Realtime/common/Common/",
    "matches/Realtime/common/Macro/",
    "matches/Realtime/client/Rust",
    "statistics/Events/server/",
    "system/Compatibility/server/",
]
