apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        prometheus: "true"
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "registry.dev.cheetah.games/cheetah/platform/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          resources:
            limits:
              cpu: {{ .Values.cpu.limit }}
              memory: {{ .Values.memory.limit }}
            requests:
              cpu: {{ .Values.cpu.request }}
              memory: {{ .Values.memory.request }}
          imagePullPolicy: Always
          startupProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: "JWT_PUBLIC_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: public
            - name: "JWT_PRIVATE_KEY"
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: private
            - name: YDB_HOST
              value: "$({{ .Release.Namespace | upper | replace "-" "_" }}_YDB_DATABASE_GRPC_SERVICE_HOST)"
            - name: YDB_NAMESPACE
              value: "/Root/{{ .Release.Namespace}}-ydb-database/"
            - name: YDB_PORT
              value: "$({{ .Release.Namespace | upper | replace "-" "_" }}_YDB_DATABASE_GRPC_SERVICE_PORT)"
            - name: "REDIS_HOST"
              value: "$(CHEETAH_ACCOUNTS_REDIS_MASTER_SERVICE_HOST)"
            - name: "REDIS_PORT"
              value: "$(CHEETAH_ACCOUNTS_REDIS_MASTER_SERVICE_PORT)"
            - name: "REDIS_AUTH"
              valueFrom:
                secretKeyRef:
                  name: cheetah-accounts-redis-password
                  key: password
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.global.lokiUrl}}
          ports:
            - name: prometheus
              containerPort: 3000
              protocol: TCP
