apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.global.grpcDomain }}
      http:
        paths:
          - pathType: Prefix
            path: /cheetah.liveops.client-version.*
            backend:
              service:
                name: "{{ .Chart.Name }}-external"
                port:
                  number: 5000