apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    configmap.reloader.stakater.com/reload: "cheetah-system-compatibility-versions"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        prometheus: "true"
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: cheetahdockerregistry
      containers:
        - name: {{ .Chart.Name }}
          image: "registry.dev.cheetah.games/cheetah/platform/{{ .Chart.Name }}:{{ .Values.global.platformImageVersion }}"
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
          startupProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:5000" ]
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: {{ .Values.cpu.limit }}
              memory: 40Mi
            requests:
              cpu: {{ .Values.cpu.request }}
              memory: 20Mi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOKI_URL
              value: {{.Values.global.lokiUrl}}
            - name: CONFIG_FILE
              value: /tmp/config/versions.yaml
          volumeMounts:
            - mountPath: /tmp/config/
              readOnly: true
              name: configurations
          ports:
            - name: prometheus
              containerPort: 3000
              protocol: TCP
      volumes:
        - name: configurations
          configMap:
            name: "cheetah-system-compatibility-versions"
